name: picpay-challenge
services:
  web:
    build: services/frontend
    ports:
      - "5000:5000"
    networks:
      - frontend
  reader:
    build: services/reader
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend
  writer:
    build: services/writer
    ports:
      - "8081:8081"
    networks:
      - backend
      - frontend
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
  frontend:
